guheyo/guheyo-web

.github/ISSUE_TEMPLATE/bug_report.md, .github/PULL_REQUEST_TEMPLATE.md, CONTRIBUTING.md
=> docs: update templates

.gitignore, app/components/base/avatar.tsx, app/components/base/cols-select-button.tsx, app/components/base/dm-dialog.tsx, app/components/base/image-carousel.tsx, app/components/base/image-slider.tsx, app/components/base/login-button.tsx, app/components/base/navbar.tsx, app/components/base/read-more.tsx, app/components/base/scrollbar.tsx, app/components/base/tabs.tsx, app/components/base/thumbnail.tsx, app/components/base/timeline-with-icon.tsx, app/components/categories/categories-navbar.tsx, app/components/posts/feed.tsx, app/components/posts/post-detail.tsx, app/components/posts/post-mock.tsx, app/components/posts/post-preview.tsx, app/components/posts/type-selector.tsx, app/components/users/roles.tsx, app/components/users/social-join-dates.tsx, app/components/users/social-logo.tsx, app/components/users/user-avatar.tsx, app/components/users/user-menu.tsx, app/components/users/user-name.tsx, app/components/users/user-profile.tsx, yarn.lock
- 렌더링 최적화
- app/components/base, categories, posts의 각 컴포넌트에 React.memo적용, Local Function에 useCallback 적용
=> feat: app/components/base, categories, posts React.memo적용, Function useCallback 적용

app/providers.tsx, package.json, tailwind.config.ts, yarn.lock
- mui 라이브러리 설치 및 세팅
- mui + tailwind > prefilght 충돌
mui docs 에서는 tailwind prefilght를 disabled 하는 방식을 권장하였으나,
기존 적용된 css가 어색해지는 문제가 있어 mui css 를 초기화하는 방식을 적용하였습니다
- https://mui.com/material-ui/getting-started/installation/#default-installation
- https://tailwindcss.com/docs/customizing-colors#using-the-default-colors
=> refactor: mui migration을 위한 설치 및 세팅

app/lib/api/guilds.ts, app/lib/query-key-factory.ts
key 값과 return 값의 불일치
guild -> all
category -> categories
https://github.com/lukemorales/query-key-factory
=> refactor: rename querykeys

app/components/base/dm-dialog.tsx, app/components/posts/post-detail.tsx
Dialog (DmDialog, PostDetailCard) -> mui 적용
- 기존 `DialogHeader` 를 시멘틱한 컴포넌트로 변경
- maxWidth, minHeight 값 추가하여 기본 크기 적용
- https://mui.com/material-ui/api/dialog/
=> refactor: mui > dialog 전환 작업

app/components/base/login-button.tsx, app/globals.css, tailwind.config.ts
login-button 컴포넌트 내부의 Menu -> mui 적용
- 기존의 material-tailwind의 Menu와 관련된 컴포넌트를 mui 기반 Menu 컴포넌트로 변경
- Menu 핸들링을 위한 이벤트 핸들러 메서드 적용 
- box-shadow 적용을 위한 커스텀 스타일 레이어 추가 (tailwind.config.js)
- https://mui.com/material-ui/react-menu/
=> refactor: login-button 전환 작업

LICENSE, package.json
1. 커뮤니티에 소스 코드를 공개하기
2. 상용 목적 사용자에 의한 권리 침해로부터 보호하기
[MariaDB](https://mariadb.com/bsl-faq-mariadb/), [materialize](https://github.com/MaterializeInc/materialize/blob/main/LICENSE)의 사례를 참고하여 BUSL v1.1 라이센스 도입
https://mariadb.com/bsl-faq-adopting/#whatis
=> docs: update license to BUSL-1.1

app/[guildName]/layout.tsx, app/[guildName]/market/offers/page.tsx, app/layout.tsx, components/base/navbar.tsx, components/base/thumbnail.tsx, components/offers/offer-detail.tsx, components/offers/offer-preview.tsx, components/users/user-profile.tsx, lib/apollo/apollo-provider.tsx
피드의 폭이 넓어서 시선이 분산됨
중요도가 떨어지는 정보 없애기
max-w-5xl 변경
프리뷰 업데이트 - 유저 이름 삭제, 프로필 썸네일 아래로 이동
=> feat: change max with to 5xl

.eslintrc.js, components/offers/offer-detail.tsx, generated/graphql.ts, lib/api/social-accounts.ts, lib/graphql/social-account.graphql
linkAccount, unlinkAccount / axios -> apollo
social-account.graphql 정의
apollo client mutate 전환
=> feat: change social accounts from axios to apollo

app/adapters/index.ts, app/api/auth/[...nextauth]/route.ts, components/offers/offer-preview.tsx, generated/graphql.ts, graphql.config.yml, lib/api/sessions.ts, lib/api/users.ts, lib/apollo/client.ts, lib/graphql/session.graphql, lib/graphql/social-account.graphql, lib/graphql/user.graphql
next auth adapter: axios -> apollo
session: axios ->apollo
query의 중복 field
expires 타입 오류
session.graphql 정의
fragment 를 통한 중복 제거
expires: DateTime ->Date
=> feat: use apollo instead of axios in next auth DatabaseAdapter, add session.graphql

app/adapters/index.ts, app/api/auth/[...nextauth]/route.ts, components/base/login-button.tsx, generated/graphql.ts, lib/api/sessions.ts, lib/api/users.ts, lib/graphql/offer.graphql, lib/graphql/social-account.graphql, lib/graphql/user-image.graphql, lib/graphql/user.graphql, package.json, yarn.lock
next-auth Naver 로그인 추가
NaverProvider에서 profile return 값 설정
name, mobile_e164 받아오기
https://developers.naver.com/products/login/api/api.md
=> feat: add naver login

app/[guildName]/market/offers/layout.tsx, app/[guildName]/market/offers/page.tsx, components/base/navbar.tsx, components/base/scrollbar.tsx, components/categories/categories-navbar.tsx
1. scroll down 시 모든 navBar 숨기기
2. offers Infinite scroll 구현
1. useScrollDirection up일 떄 상단 고정
2. useInfiniteScroll 과 fetchMore, updateQuery 이용
https://www.apollographql.com/docs/react/v2/data/pagination/
=> feat: add graphql infinite scroll to offers

app/[guildName]/market/demands/layout.tsx, app/[guildName]/market/demands/page.tsx, app/[guildName]/market/offers/layout.tsx, app/[guildName]/market/offers/page.tsx, components/base/navbar.tsx, components/categories/categories-navbar.tsx, components/demands/demand-detail.tsx, components/demands/demand-preview.tsx, components/offers/offer-detail.tsx, components/offers/offer-preview.tsx, generated/graphql.ts, lib/graphql/demand.graphql, lib/graphql/user.graphql
삽니다 채널 추가
add demand.graphql, demand layout, page
=> feat: add demand page

app/[guildName]/market/demands/layout.tsx, app/[guildName]/market/offers/layout.tsx, app/[guildName]/market/swaps/layout.tsx, app/about/page.tsx, components/categories/categories-navbar.tsx, generated/graphql.ts, lib/graphql/guild.graphql
home url에서 이동하지 않고, 곧바로 categoryId가 포함된 url로 접속하였을 때 navBar가 뜨지 않는 버그
Product Categories Navbar에서 useFindGuildsQuery를 통해 직접 Categories를 가져 오도록 변경
=> feat: fetch guild in CategoriesNavbar

LICENSE, app/[guildName]/market/demands/layout.tsx, app/[guildName]/market/demands/page.tsx, app/[guildName]/market/offers/layout.tsx, app/[guildName]/market/offers/page.tsx, app/[guildName]/market/swaps/layout.tsx, app/[guildName]/market/swaps/page.tsx, app/page.tsx, components/base/cols-select-button.tsx, components/categories/categories-navbar.tsx, components/deals/deal-selector.tsx, lib/apollo/cache.ts
pathname으로부터 deal type을 가져오면 selector value에 표시되기까지 오랜 시간이 걸림
useReactiveVar를 이용하여 deal type 관리
https://www.apollographql.com/docs/react/local-state/reactive-variables/
=> feat: add deal-selector

app/g/[guildSlug]/layout.tsx, app/layout.tsx, app/page.tsx, components/base/navbar.tsx, components/categories/categories-navbar.tsx, components/deals/deal-selector.tsx, components/demands/demand-feed.tsx, components/demands/demand-preview.tsx, components/guilds/guild-feed.tsx, components/guilds/guild-info.tsx, components/guilds/guild-join-button.tsx, components/guilds/guild-preview.tsx, components/offers/offer-preview.tsx, components/posts/post-dialog.tsx, components/swaps/swap-preview.tsx
layout 업데이트
font 사이즈 조정
naverbar top 위치 조정
=> feat: update layout

app/error.tsx, components/guilds/guild-info.tsx, components/offers/offer-detail.tsx, components/offers/offer-preview.tsx, components/swaps/swap-preview.tsx
guild.icon 값이 null 일 때 발생하는 에러
guild.icon 이 없을 경우 star logo를 사용
=> fix: handle null case of guild.icon

app/g/[groupSlug]/market/demands/page.tsx, app/g/[groupSlug]/market/offers/page.tsx, app/g/[groupSlug]/market/swaps/page.tsx, app/g/[groupSlug]/page.tsx, app/search/layout.tsx, components/base/image-slider.tsx, components/categories/categories-navbar.tsx, components/demands/demand-feed.tsx, components/groups/group-header.tsx, components/groups/group-info.tsx, components/offers/offer-feed.tsx, components/search/product-search-results.tsx, components/search/search-groups.tsx, components/search/search-input.tsx, components/search/search-products.tsx, components/swaps/swap-feed.tsx, generated/graphql.ts, hooks/use-device-detect.ts, hooks/use-group.ts, hooks/use-infinite-demand-feed.ts, hooks/use-infinite-offer-feed.ts, hooks/use-infinite-swap-feed.ts, interfaces/deal.interfaces.ts, lib/graphql/demand.graphql, lib/graphql/offer.graphql, lib/graphql/swap.graphql
1. feed 정렬
2. product saerch results에서 category 보여주기
1. feed의 props 으로 where, orderBy args 추가
2. categoriesNavbar 에 deal selector를 숨기는 옵션 추가
=> feat: add where, orderBy props in Deal Feed

components/images/image.previews.tsx, components/write/deal-form.tsx, generated/graphql.ts, lib/api/user-image.ts, lib/graphql/user-image.graphql, lib/image/image.colors.ts, lib/image/image.constants.ts, lib/image/image.styles.ts
1. close button으로 upload 된 image 지우기
1. useFieldArray의 remove를 활용하여 onClick으로 처리
https://react-hook-form.com/docs/usefieldarray
=> feat: delete userImage by clicking close button in image-preview

app/write/g/[groupSlug]/market/demand/[id]/page.tsx, app/write/g/[groupSlug]/market/offer/[id]/page.tsx, app/write/g/[groupSlug]/market/page.tsx, app/write/g/[groupSlug]/market/swap/[id]/page.tsx, components/inputs/button-inputs.tsx, components/inputs/images-input.tsx, components/write/deal-form.tsx, components/write/edit-deal-form.tsx, components/write/write-deal-form.tsx, generated/graphql.ts, lib/api/demand.ts, lib/api/offer.ts, lib/api/swap.ts, lib/deal/deal.interfaces.ts, lib/deal/parse-create-deal-input.ts, lib/deal/parse-deal-description-placeholder.ts, lib/deal/parse-deal-options.ts, lib/deal/parse-prev-form-values.ts, lib/deal/parse-temp-deal-form-key.ts, lib/deal/parse-update-deal-input.ts, lib/deal/update-deal.ts, lib/graphql/demand.graphql, lib/graphql/offer.graphql, lib/graphql/swap.graphql, lib/image/image.styles.ts
글 수정
1. deal-form -> write-deal-form 리팩토링
2. edit-deal-form 추가
=> feat: add edit-deal-form

components/deals/deal-menu.tsx, components/deals/private-deal-menu.tsx, components/write/edit-deal-form.tsx, generated/graphql.ts, lib/api/deal.ts, lib/deal/deal.types.ts, lib/deal/parse-update-deal-input.ts
거래 상태 변경 버튼 추가
private deal menu 에 버튼, handle logic 추가
=> feat: add buttons to change the deal status

components/base/login-button.tsx, components/deals/deal-preview.tsx, components/deals/deal-report-form.tsx, components/deals/deal-text-preview.tsx, components/deals/deal-thumbnail-preview.tsx, components/demands/demand-preview.tsx, components/offers/offer-preview.tsx, components/reports/reports-count.tsx, components/swaps/swap-preview-preview.tsx, generated/graphql.ts, lib/graphql/comment.graphql, lib/graphql/demand.graphql, lib/graphql/offer.graphql, lib/graphql/report.graphql, lib/graphql/swap.graphql
신고가 들어온 게시글에 피신고 횟수 표시하기
1. 단순 신고 횟수 카운트를 위한 ReportResponse와 author가 포함된 ReportWithAuthorResponse 분리
2. ReportsCount component 생성
=> feat: show reports count in preview

components/reports/report-comment-card.tsx, generated/graphql.ts, lib/api/demand.ts, lib/api/swap.ts, lib/deal/comment-deal-report.ts, lib/graphql/demand.graphql, lib/graphql/swap.graphql
demand, swap report에 댓글 달기
comment deal report - offer, demand, swap
=> feat: comment on the demand and swap reports

components/comments/comment-card.tsx, components/comments/comment-menu.tsx, components/comments/comment-output.tsx, components/deals/private-deal-menu.tsx, components/reports/report-card.tsx, components/reports/report-comment-card.tsx, components/reports/report-feed.tsx, components/reports/report-preview.tsx, generated/graphql.ts, hooks/use-infinite-reports.ts, interfaces/report.interfaces.ts, lib/api/comment.ts, lib/comment/parse-comment-date.ts, lib/graphql/comment.graphql, lib/graphql/report.graphql
댓글 수정하기
1. updateComment mutation을 통한 수정
2. 수정된 결과값을 apollo cache에 업데이트 - writeQuery
https://dev.to/lucis/update-apollo-cache-after-a-mutation-and-get-instant-benefits-on-your-ui-1c3b
=> feat: update comment

app/report/[type]/[refId]/page.tsx, app/version/(deal-detail)/demand/[id]/page.tsx, app/version/(deal-detail)/layout.tsx, app/version/(deal-detail)/offer/[id]/page.tsx, app/version/(deal-detail)/swap/[id]/page.tsx, components/base/login-button.tsx, components/comments/comment-output.tsx, components/deals/deal-addons.tsx, components/deals/deal-detail-main.tsx, components/deals/deal-text-preview.tsx, components/deals/deal-thumbnail-preview.tsx, components/deals/deal-version-detail-main.tsx, components/deals/deal-version-detail.tsx, components/reports/report-card.tsx, components/reports/report-comment-card.tsx, components/reports/report-comment-title.tsx, components/reports/report-comments-count.tsx, components/reports/report-feed.tsx, components/reports/report-preview.tsx, components/reports/reports-count.tsx, components/reports/reports-link.tsx, components/version/recent-version-link.tsx, generated/graphql.ts, lib/comment/parse-comment-date.ts, lib/graphql/user.graphql, lib/graphql/version.graphql, lib/link/parse-user-page.link.ts, lib/link/parse-version-page.link.ts
신고 접수된 시점의 거래글 version 확인
1. 신고 시점의 version page로 링크되는 버튼 생성
2. DealVersionDetail component생성
3. offer, demand, swap 각각의 version page 생성
=> feat: add deal version page

components/deals/private-deal-menu.tsx, components/posts/post-delete-dialog.tsx, components/search/search-groups.tsx, components/search/search-products.tsx, generated/graphql.ts, lib/api/deal.ts, lib/api/demand.ts, lib/api/offer.ts, lib/api/swap.ts, lib/graphql/demand.graphql, lib/graphql/offer.graphql, lib/graphql/swap.graphql
게시글 삭제 버튼 추가
1. delete mutation graphql 추가
2. implement PostDeleteDialog
3. private deal menu 삭제 item 추가
https://mui.com/material-ui/react-dialog/
=> feat: add post-delete-dialog, add delete button in deal-menu

app/user/[username]/(home)/(deal-feed)/layout.tsx, components/comments/comment-output.tsx, components/deals/deal-detail-main.tsx, components/deals/deal-detail.tsx, components/deals/deal-menu.tsx, components/deals/deal-preview.tsx, components/deals/deal-status-selector.tsx, components/deals/deal-text-preview.tsx, components/deals/deal-thumbnail-preview.tsx, components/deals/my-feed-home.layout.tsx, components/deals/private-deal-menu.tsx, components/demands/demand-feed.tsx, components/offers/offer-feed.tsx, components/reports/report-alert-dialog.tsx, components/reports/report-comment-card.tsx, components/reports/report-comment-title.tsx, components/reports/reports-link.tsx, components/swaps/swap-feed.tsx, components/users/my-user-deal-status-navbar.tsx, lib/deal/deal.constants.ts, lib/deal/deal.types.ts, lib/deal/parse-deal-status.ts
1. 신고 접수된 거래글의 상태 임의 변경 막기
2. user home feed의 filtering 변수 변경
1. ReportAlertDialog
2. hidden status 추가, 필터링 항목 선택 방법을 selector -> buttons로 변경
=> feat: add hidden status, my user deal status navbar

components/categories/categories-navbar.tsx, components/deals/deal-detail-main.tsx, components/deals/deal-menu.tsx, components/deals/deal-preview.tsx, components/deals/deal-selector.tsx, components/deals/deal-text-preview.tsx, components/deals/deal-thumbnail-preview.tsx, components/deals/private-deal-menu.tsx, components/demands/demand-feed.tsx, components/demands/demand-preview.tsx, components/offers/offer-feed.tsx, components/offers/offer-preview.tsx, components/selectors/query-selector.tsx, components/swaps/swap-feed.tsx, components/swaps/swap-preview.tsx, components/users/my-deal-status-navbar.tsx, components/users/user-profile-popper.tsx, components/write/deal-form.tsx, generated/graphql.ts, interfaces/deal.interfaces.ts, lib/deal/deal.constants.ts, lib/deal/deal.types.ts, lib/discord/parse-discord-dm-link.ts, lib/graphql/demand.graphql, lib/graphql/offer.graphql, lib/graphql/swap.graphql, lib/query-string/create-query-string.ts, lib/user/get-discord-id.ts
1. 거래글 상태에 따라 private deal menu가 다른 항목들을 보여줘야 함
1. private deal menu 에 status, isHidden props를 추가하여, 이를 통한 option들을 전달
=> feat: update private deal-menu, add isHidden field

app/setting/profile/page.tsx, app/user/[username]/(home)/deal/layout.tsx, components/auth/auth.provider.tsx, components/auth/discord-login-dialog.tsx, components/base/login-button.tsx, components/deals/deal-menu.tsx, components/deals/deal-report-form.tsx, components/demands/demand-bump-form.tsx, components/offers/offer-bump-form.tsx, components/reports/report-comment-card.tsx, components/swaps/swap-bump-form.tsx, components/users/user-home-navbar.tsx, components/users/user-profile.tsx, components/write/edit-deal-form.tsx, components/write/write-deal-form.tsx, interfaces/auth.interfaces.ts, lib/auth/get-jwt-payload.ts
jwt payload 인 auth user가 social profile 정보와 user 데이터가 혼재되어 명확하지 않은 문제
1. SocialProfile, UserPayload, JwtPayload 로 분리
=> feat: update auth interface to SocialProfile, UserPayload, JwtPayload

generated/graphql.ts, interfaces/auth.interfaces.ts, lib/graphql/user.graphql
jwt로 member roles 관리
1. jwtPayload에 memberRoles 를 포함하여 cookie로 저장
=> feat: add memberRoles in jwtPayload

components/base/login-button.tsx, components/deals/deal-detail-name.tsx, components/deals/deal-menu.tsx, components/groups/gorup-join-button.tsx, components/posts/post-delete-dialog.tsx, components/reports/report-alert-dialog.tsx, components/socials/discord-profile-linker.tsx, components/write/write-button.tsx
submit 버튼 클릭 후 로딩 효과 주기
일반 버튼 -> mui의 loading button
https://mui.com/material-ui/api/loading-button/
=> feat: add loading button

components/base/login-button.tsx, components/demands/demand-feed.tsx, components/groups/gorup-join-button.tsx, components/offers/offer-feed.tsx, components/swaps/swap-feed.tsx, components/write/deal-form.tsx, components/write/write-button.tsx, lib/deal/deal.constants.ts, lib/deal/parse-deal-status.ts
1. feed의 where args에서 isHidden 일 때 status가 open으로 고정되는 문제 
2. 이미지 업로드 주의 문구 추가
3. fext field의 숫자 입력시 0 이상의 숫자로 제한
1. 모든 status를 선택할 경우 undefined로 설정
2. 아이디 인증 메모 언급
3. min: 0으로 설정
=> feat: update deal form

components/auth/discord-login-dialog.tsx, components/auth/logged-in-user-alert-dialog.tsx, components/auth/logged-in-user-button.tsx, components/auth/login-button.tsx, components/base/navbar.tsx, components/reports/reports-alert-dialog.tsx, lib/group/group.constants.ts, lib/role/find-member-roles.ts, lib/role/has-reported-user-role.ts, lib/role/is-reported-user.ts, lib/role/role.constants.ts, lib/user/parse-user-page.link.ts
미답변 신고가 생긴 유저에게 신고 알림 alert을 띄우기
1. 로그인 유저가 hasReportedUserRole 에 해당할 경우 alert 띄우기
2. ReportsAlertDialog 을 띄운 후 user reports 피드로 link
=> feat: alert for reported user

app/g/[groupSlug]/market/demand/page.tsx, app/g/[groupSlug]/market/offer/page.tsx, app/g/[groupSlug]/market/swap/page.tsx, app/user/[username]/(home)/deal/demand/page.tsx, app/user/[username]/(home)/deal/offer/page.tsx, app/user/[username]/(home)/deal/swap/page.tsx, components/auth/logged-in-user-button.tsx, components/demands/demand-feed.tsx, components/inputs/accordion-input.tsx, components/offers/offer-feed.tsx, components/search/product-search-results.tsx, components/setting/setting-about.tsx, components/swaps/swap-feed.tsx, components/users/private-user-profile.tsx, generated/graphql.ts, lib/api/user.ts, lib/date/date.converter.ts, lib/graphql/user.graphql, lib/report/report.constants.ts, lib/report/report.interfaces.ts
1. 장터, 검색 페이지에서는 중복 제거가 기본 옵션이지만, my feed를 볼 때는 전체 보기로 설정되어야 함
2. 신고 사유 목록 중 선택 불가 항목 적용
1. feed에서의 distinct default 값을 없애고, params으로 pass
2. disabled option을 통해 선택 제한
=> feat: remove default distinct value in feed

components/auth/login-button.tsx, components/deals/deal-bump-form.tsx, components/deals/deal-report-form.tsx, components/demands/demand-feed.tsx, components/inputs/accordion-input.tsx, components/offers/offer-feed.tsx, components/reports/reports-alert-dialog.tsx, components/search/product-search-results.tsx, components/setting/setting-about-form.tsx, components/swaps/swap-feed.tsx, components/write/deal-form.tsx, lib/deal/find-deal-label.ts, lib/deal/parse-deal-bump-form-title.ts, lib/deal/parse-deal-price-name.ts, lib/report/report.constants.ts, lib/role/find-member-roles.ts, lib/role/has-reported-user-role.ts
=> style: lint

app/edit/demand/[id]/page.tsx, app/edit/offer/[id]/page.tsx, app/edit/swap/[id]/page.tsx, app/report/[type]/[refId]/page.tsx, app/version/(deal-detail)/demand/[id]/page.tsx, app/version/(deal-detail)/offer/[id]/page.tsx, app/version/(deal-detail)/swap/[id]/page.tsx, components/demands/demand-bump-form.tsx, components/demands/demand-detail.tsx, components/demands/demand-report.tsx, components/groups/group-feed.tsx, components/offers/offer-bump-form.tsx, components/offers/offer-detail.tsx, components/offers/offer-report.tsx, components/reports/report-card.tsx, components/reports/report-comment-card.tsx, components/setting/setting-about.tsx, components/swaps/swap-detail.tsx, components/swaps/swap-report.tsx, components/term/term.tsx, components/users/private-user-profile.tsx, hooks/use-infinite-demand-feed.ts, hooks/use-infinite-offer-feed.ts, hooks/use-infinite-reports.ts, hooks/use-infinite-swap-feed.ts
feed에서 상세 페이지 클릭 후 되돌아올 경우 상단 페이지로 위치하는 문제
1. fetchPolicy: network-only -> cache-and-network
https://www.apollographql.com/docs/react/data/queries/
=> feat: update infinite scroll feed fetch policy

app/g/[groupSlug]/market/demand/page.tsx, app/g/[groupSlug]/market/offer/page.tsx, app/g/[groupSlug]/market/swap/page.tsx, app/user/[username]/(home)/deal/demand/page.tsx, app/user/[username]/(home)/deal/offer/page.tsx, app/user/[username]/(home)/deal/swap/page.tsx, components/deals/deal-detail-main.tsx, components/deals/deal-detail.tsx, components/deals/private-deal-menu.tsx, components/demands/demand-detail.tsx, components/demands/demand-feed.tsx, components/offers/offer-detail.tsx, components/offers/offer-feed.tsx, components/search/product-search-results.tsx, components/swaps/swap-detail.tsx, components/swaps/swap-feed.tsx
1. 장터, user home에서 deal feed의 status의 default 값을 다르게 주어야 하는 문제
2. DealDetailMain의 isHidden props 누락
3. deal menu에서 update, delete 이후 알림 주기
1. status를 feed의 props으로 이동
2. DealDetailMain에 isHidden props 추가
3. alert
=> feat: update deal feed props

components/base/alert-dialog.tsx, components/demands/demand-bump-form.tsx, components/offers/offer-bump-form.tsx, components/swaps/swap-bump-form.tsx, components/write/write-deal-form.tsx, generated/graphql.ts, lib/api/deal.ts, lib/api/demand.ts, lib/api/offer.ts, lib/api/swap.ts, lib/date/date.constants.ts, lib/deal/deal.constants.ts, lib/deal/is-posting-limit-exceeded-error.ts, lib/deal/parse-deal-term-alert-message.ts, lib/deal/validate-deal-term.ts, lib/graphql/demand.graphql, lib/graphql/group.graphql, lib/graphql/offer.graphql, lib/graphql/swap.graphql
1. 일일 거래글 작성 한도 초과시, 초과 안내
1. create 또는 bump 후 posting limit exceeded 메시지가 있으면 alert 띄우기
=> feat: add deal-term alert in deal-write-form, bump-form

components/deals/deal-report-form.tsx, components/demands/demand-bump-form.tsx, components/offers/offer-bump-form.tsx, components/reports/report-submit-button.tsx, components/swaps/swap-bump-form.tsx, generated/graphql.ts, lib/date/find-time-left-until-cooldown-ends.ts, lib/date/validate-cooldown.ts, lib/deal/find-time-left-until-bump-cooldown-ends.ts, lib/deal/parse-deal-bump-button-name.ts, lib/deal/validate-bump.ts, lib/graphql/report.graphql, lib/report/parse-report-button-name.ts
report 일일 허용 횟수를 초과하였을 경우, 다음 신고까지 남은 시간 알려주기
1. findLastReport를 통해 마지막 report.createdAt 찾기
2. validateCooldown을 통해 검증
3. cooldown이 남아 있을 경우 버튼에 남은 시간 표시
=> feat: add report submit button with cooldown

generated/graphql.ts, lib/graphql/term.graphql
=> feat: update term response (#140)

app/policy/layout.tsx, generated/graphql.ts
1. policy text가 최하단까지 닿는 문제
2. bot bulk-save 처리를 위한 create input update
1. pb-10
2. create input variables 추가
=> feat: update policy layout

app/report/[type]/[refId]/page.tsx, components/deals/deal-review-form.tsx, components/deals/manner-tag-button-inputs.tsx, generated/graphql.ts, lib/api/deal-review.ts, lib/deal/deal.interfaces.ts, lib/deal/parse-deal-review-form-title.ts, lib/deal/parse-dealer-id.ts, lib/graphql/deal-review.graphql, lib/graphql/manner-tag.graphql
거래 후기 작성 폼 만들기
1. deal-review, manner-tag graphql
2. mannerTags를 선택할 수 있는 button inputs
거래 후기 작성 폼으로 넘어가기 전에, reviewee 검색 후 선택하기
=> feat: add draft deal review form

app/g/[groupSlug]/(community)/member/layout.tsx, app/search/g/[slug]/member/page.tsx, components/search/search-button.tsx, components/search/search-users.tsx, components/users/user-feed-layout.tsx, components/users/user-feed.tsx
group 멤버 검색
1. SearchUsers
2. add link to UserPreview, redirect to user home page
=> feat: add SearchUsers

app/g/[groupSlug]/layout.tsx, app/layout.tsx, app/page.tsx, components/base/navbar.tsx, components/base/sidebar-item.tsx, components/groups/group-bottom-navbar.tsx, components/groups/group-header-item.tsx, components/groups/group-header.tsx, components/groups/group-join-section.tsx, components/groups/group-preview.tsx, components/groups/group-profile-sidebar-items.tsx, components/groups/group-profile.tsx, components/groups/group-sidebar.tsx, components/info/info-card.tsx, components/search/search-button.tsx, components/users/user-avatar.tsx
1. mobile에서 sidebar 활용하기
2. sidebar 그룹 탭에 group profile list 보여주기
1. menu icon으로 sidebar 펼치기 - layout에서 isMenuOpen, toggleMenu 관리
2. group-profile-sidebar-items
=> feat: add sidebar menu in mobile, update sidebar layout

app/write/review/offer/[offerId]/page.tsx, app/write/review/user/[userId]/page.tsx, components/offers/offer-checkbox-results.tsx, components/users/user-checkbox-results.tsx, lib/offer/offer.interfaces.ts, lib/search/search.types.ts
내 거래글로부터 유저 리뷰 작성하기
1. 거래 대상자 찾기 - SearchInput, UserCheckboxResults
2. offerId, userId 를 통해 Write UserReviewForm Page로 넘어가기
=> feat: search user and link to write userReviewForm page

app/g/[groupSlug]/(community)/review/layout.tsx, app/user/[username]/(home)/review/layout.tsx, app/user/[username]/(home)/review/page.tsx, app/user/[username]/(home)/review/received/page.tsx, app/user/[username]/(home)/review/submitted/page.tsx, components/user-review/manner-tags-navbar.tsx, components/user-review/user-review-feed.tsx, components/user-review/user-review-submitter-navbar.tsx, components/users/user-home.constants.ts, interfaces/user-review.interfaces.ts, lib/user-review/user-review.constants.ts
1. 거래 후기 피드에서 매너, 비매너 태그로 필터링
2. 유저 홈에서에 받은 후기, 보낸 후기 보기
1. mannerTagsNavbar - where args에 tagType  추가
2. received user-review feed, submitted user-review feed - where args에 reviewedUserId 추가
=> feat: add mannerTagsNavbar, user-review feed in user home

app/review/[userReviewSlug]/page.tsx, app/review/layout.tsx, components/base/thumbnail.tsx, components/offers/offer-preview-footer.tsx, components/offers/offer-thumbnail-preview.tsx, components/posts/post-addons.tsx, components/posts/post-created-at.tsx, components/posts/post-detail-name.tsx, components/user-review/user-review-detail-main.tsx, components/user-review/user-review-detail.tsx, components/user-review/user-review-preview-content.tsx, components/user-review/user-review-preview-header.tsx, components/user-review/user-review-tags.tsx, components/user-review/user-review-text-preview.tsx, generated/graphql.ts, lib/graphql/user-review.graphql
1. user review preview에 thumbnail, content 정보 추가
2. user review detail page
1. UserReviewPreviewContent
2-1. findUserReview
2-2. UserReviewDetail
=> feat: add UserReviewPreviewContent, UserReviewDetail

app/offer/[slug]/page.tsx, app/offer/[slug]/review/page.tsx, components/groups/group-profile-sidebar-items.tsx
1. 신고가 있을 때만 신고 갯수 표시
2. useInfiniteGroupProfiles의 take 변경
1. offer.post.reportCount > 0 condition 추가
2. take 1 -> 3
=> feat: update report count in offer detail page

app/g/[groupSlug]/(community)/member/layout.tsx, app/g/[groupSlug]/(community)/report/layout.tsx, app/g/[groupSlug]/(community)/review/layout.tsx, app/g/[groupSlug]/layout.tsx, app/g/[groupSlug]/page.tsx, components/categories/categories-navbar.tsx, components/member/member-roles-navbar.tsx, components/offers/offer-feed-home.layout.tsx, components/reports/report-type-navbar.tsx, components/setting/setting-profile-navbar.tsx, components/user-review/manner-tags-navbar.tsx, components/users/user-home-navbar.tsx
1. 모바일에서 navbar item font size 키우기
2. 모바일에서 navbar가 왼쪽 모서리와 닿는 문제
1. text-xs -> text-sm
2. px
=> feat: update font size, px in navbar items

app/g/[groupSlug]/(community)/member/layout.tsx, app/g/[groupSlug]/(community)/report/layout.tsx, app/g/[groupSlug]/(community)/review/layout.tsx, app/g/[groupSlug]/layout.tsx, app/g/[groupSlug]/page.tsx, components/categories/categories-navbar.tsx, components/member/member-roles-navbar.tsx, components/offers/offer-feed-home.layout.tsx, components/reports/report-type-navbar.tsx, components/setting/setting-profile-navbar.tsx, components/user-review/manner-tags-navbar.tsx, components/users/user-home-navbar.tsx
* feat: use client in group home page
* feat: update size props
* feat: update categories-navbar font size
* feat: update px
* feat: update font size in navbar label
* build(deps): bump next from 14.1.0 to 14.1.1
Bumps [next](https://github.com/vercel/next.js) from 14.1.0 to 14.1.1.
- [Release notes](https://github.com/vercel/next.js/releases)
- [Changelog](https://github.com/vercel/next.js/blob/canary/release.js)
- [Commits](https://github.com/vercel/next.js/compare/v14.1.0...v14.1.1)
---
updated-dependencies:
- dependency-name: next dependency-type: direct:production ...
* build(deps): bump tar from 6.2.0 to 6.2.1
Bumps [tar](https://github.com/isaacs/node-tar) from 6.2.0 to 6.2.1.
- [Release notes](https://github.com/isaacs/node-tar/releases)
- …
=> feat: update font size, px in navbar items (#183)

app/g/[groupSlug]/page.tsx, app/layout.tsx, components/footers/home-footer.tsx, components/offers/offer-detail-main.tsx, components/offers/offer-detail-name.tsx, components/offers/offer-menu.tsx, components/offers/offer-version-detail-main.tsx, components/posts/post-preview-title.tsx, components/swaps/swap-name.tsx, components/user-review/user-review-detail-main.tsx
* feat: update redirect path
* feat: resize fontsize
* feat: set overflow-x-hidden in root layout
* feat: update pt
* feat: add pb-6 in root layout
* feat: remove mr
* feat: add length in SwapName props
=> feat: update detail page font size, layout (#185)

app/g/[groupSlug]/(market)/page.tsx, components/base/back-drop.tsx, components/base/navbar.tsx, components/comments/comment-card.tsx, components/groups/group-preview.tsx, components/groups/group-sidebar.tsx, components/offers/offer-feed-home.layout.tsx, components/search/search-products.tsx, lib/user-review/user-review.constants.ts
1. mobile에서 댓글을 키입력으로 전송하기 어려움
2. 카테고리 navbar의 background가 수평 방향 모서리를 전부 채우지 못하는 문제
1. 전송 버튼 - UpwardIcon
2. px -> mx w-full
=> feat: add send button in comment input, update categories navbar style

app/report/[id]/page.tsx, components/offers/offer-detail-main.tsx, components/offers/offer-version-detail-main.tsx, components/posts/post-detail-addons.tsx, components/posts/post-preview-addons.tsx, components/share/share-button.tsx, components/user-review/user-review-detail-main.tsx, components/user-review/user-review-preview-footer.tsx
공유 버튼 추가
1. clipboard 로 주소 복사
2. icon 클릭시 dialog open
3. tooltip
https://mui.com/material-ui/react-tooltip/
=> feat: add share button

app/report/[id]/page.tsx, app/write/review/offer/[offerId]/page.tsx, app/write/review/user/[userId]/page.tsx, components/comments/comment-card.tsx, components/info/info-feed-layout.tsx, components/offers/offer-checkbox-results.tsx, components/offers/offer-detail-main.tsx, components/offers/offer-version-detail-main.tsx, components/posts/post-detail-addons.tsx, components/posts/post-preview-addons.tsx, components/search/product-search-results.tsx, components/share/share-button.tsx, components/user-review/user-review-detail-main.tsx, components/user-review/user-review-preview-footer.tsx, components/users/user-checkbox-results.tsx, hooks/use-infinite-scroll.ts
1. 한글키 중복 입력 문제
2. CheckboxResults에서의 intersection 미감지 문제
3. 공유 버튼 추가
#189
#190
=> fix: handle double input problem of korean keys, add share button

components/share/share-button.tsx
=> feat: remove semicolon

components/base/back-drop.tsx, components/groups/group-sidebar.tsx, components/offers/offer-detail-main.tsx, components/offers/offer-version-detail-main.tsx
1. 이모지 선택창을 열 때, 배경이 어두워지는 문제
2. 공유 버튼 위치 조절
1. BackDrop의 backgroundColor, opacity를 props로 관리
2. 본문과의 간격을 pt-14로 변경
=> feat: add backgroundColor, opacity as props in BackDrop

components/base/back-drop.tsx, components/groups/group-sidebar.tsx, components/offers/offer-detail-main.tsx, components/offers/offer-version-detail-main.tsx
* feat: update pt
* feat: ad backgroundColor, opacity as props in BackDrop
=> feat: add backgroundColor, opacity as props in BackDrop (#193)

components/user-review/private-user-review-menu.tsx, components/user-review/user-review-detail-main.tsx, components/user-review/user-review-menu.tsx, generated/graphql.ts, lib/api/user-review.ts, lib/graphql/comment.graphql, lib/graphql/group.graphql, lib/graphql/offer.graphql, lib/graphql/post.graphql, lib/graphql/reaction.graphql, lib/graphql/report.graphql, lib/graphql/tag.graphql, lib/graphql/term.graphql, lib/graphql/user-review.graphql, lib/graphql/user.graphql, lib/graphql/version.graphql
거래 후기 삭제
1. delete user review mutation
2. UserReviewMenu
=> feat: add user review menu for deleting review

app/about/layout.tsx, app/bump/layout.tsx, app/edit/layout.tsx, app/g/[groupSlug]/layout.tsx, app/offer/[slug]/layout.tsx, app/policy/privacy/layout.tsx, app/policy/rule/layout.tsx, app/policy/service/layout.tsx, app/report/layout.tsx, app/review/[userReviewSlug]/layout.tsx, app/search/g/[slug]/member/layout.tsx, app/search/g/[slug]/product/layout.tsx, app/search/layout.tsx, app/user/[username]/layout.tsx, app/write/layout.tsx, components/groups/group-bottom-navbar.tsx, components/share/share-button.tsx, lib/url/parse-slug-from-url.ts
페이지별로 title, description 설정하기
1. static datat - metadata
1. dynamic data - generateMetadata
https://nextjs.org/docs/app/api-reference/functions/generate-metadata
=> feat: add metadata in each pages

app/g/[groupSlug]/(market)/[businessFunction]/page.tsx, app/user/[username]/(home)/offer/[businessFunction]/page.tsx, components/offers/offer-checkbox-results.tsx, components/offers/offer-feed.tsx, components/search/product-search-results.tsx, components/user-review/user-review-feed.tsx, interfaces/user-review.interfaces.ts
1. where args props 정리
2. User Home에서 거래글의 상태 필터가 open으로 설정되어 있는 문제
1.status -> where.status
2. status = undefined로 모든 상태의 거래글 불러오기
=> feat: move status to where.status in Feed props

app/g/[groupSlug]/(market)/[businessFunction]/page.tsx, app/user/[username]/(home)/offer/[businessFunction]/page.tsx, components/offers/offer-checkbox-results.tsx, components/offers/offer-feed.tsx, components/search/product-search-results.tsx, components/user-review/user-review-feed.tsx, interfaces/user-review.interfaces.ts
* feat: remove status, use where.status in offer checkbox results props
* feat: move status to where.status
* feat: move status to where.status in UserReviewFeed
=> feat: move status to where.status in Feed props (#198)

app/user/[username]/(home)/offer/[businessFunction]/page.tsx, components/offers/offer-status-navbar.tsx, components/offers/private-offer-menu.tsx, lib/offer/offer.constants.ts
1. 보관 -> 꺼내기로의 상태 변경이 안되는 문제
2. user home offer feed 의 default status 변경
1. archivedAt의 value : undefined -> null
2. public user - all, private user - open
=> fix: change isArchived value from undefined to null, update default status in user home offer feed

app/user/[username]/(home)/offer/[businessFunction]/page.tsx, components/offers/offer-bump-form.tsx, components/offers/offer-feed.tsx, components/posts/post-report-form.tsx, components/user-review/user-review-form.tsx, lib/input/input.props.ts, lib/user-review/parse-user-review-form-title.ts
1. 보관된 거래글을 불러올 때 전체가 아닌 open 상태의 거래글만 불러오는 문제
2. 거래 후기 작성폼의 제목 띄어쓰기 조절
3. 작성 폼의 폰트 사이즈 조절
1. isArchived에 따른 default status 값 변경
2. 두 번째 줄의 공백제거
3. mobile에서 너무 크게 보이지 않도록 폰트 사이즈 줄이기
=> feat: set default status according to isArchived in OfferFeed, update font sizes in form
